### ISSUE TITLE
Inference algorithm

### ISSUE THREAD

**Issue by evelinag** [dfm/george#1]
Hi, 
I'd just like to ask you what algorithm do you use for inference in your Gaussian processes. I see you're using some sort of truncated squared exponential kernel - what kernel is that exactly? Can you point me to any resources that you've been using to implement this? 
Thank you!

**Comment by dfm** [comment]
It's been many years and clearly I'm bad at responding to issues, but if anyone is interested, there are many details in the docs now: http://george.readthedocs.io/
