### ISSUE TITLE
code for "Tutorial: model fitting with correlated noise"

### ISSUE THREAD

**Issue by zygmuntz** [dfm/george#10]
Please make the code in the tutorial copy-and-paste'able: provide a function for generating _data_, set _nwalkers_, etc.

**Comment by jcatanz** [comment]
I did "pip install triangle", but I still get the error 

AttributeError: 'module' object has no attribute 'corner'

for the lines that refer to triangle.corner

**Comment by dfm** [comment]
Try:

```
pip uninstall triangle
pip install triangle-plot
```

Or install from [GitHub](https://github.com/dan/triangle.py).

**Comment by dfm** [comment]
Whoops. Typo: https://github.com/dfm/triangle.py

**Comment by jcatanz** [comment]
Thanks Dan -- that fixed the problem.

Cheers,

--jcat
