### ISSUE TITLE
Non logarithmic-only parameters 

### ISSUE THREAD

**Issue by stefanocovino** [dfm/george#126]
Dear friends,

I am modelling a problem with the sum of two kernel functions, e.f. A*K1 + B*K2, and I would be interested to know the how far from zero B is. However, within George, B is just a constant kernel and the parameter is always logarithmic. Is there a way to avoid this behaviour? 

Thanks for the attention.

   Stefano

**Comment by dfm** [comment]
You'll need to implement this using a custom kernel: https://george.readthedocs.io/en/latest/tutorials/new-kernel/

Make sure that you can demonstrate that it's positive definite!

**Comment by stefanocovino** [comment]
Hello Dan, 

Thanks a lot. For my specific problem is enough that B >= 0. So it should be a fair kernel. In general, running George, is there a warning or an error if the positive definite condition is not met?

Bye,
  Stefano

**Comment by dfm** [comment]
In that case, just make your lower bound log(1e-15) or something and it'll work just fine. 1e-15 *is* zero! 

George will throw an error if there are numerical issues, but that isn't the same as using a valid positive definite kernel!

**Comment by stefanocovino** [comment]
Thanks,
   Stefano
