### ISSUE TITLE
Build fails on mac catalina

### ISSUE THREAD

**Issue by kennychowdhary** [dfm/george#137]
After running pip install I get errors of the following type:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: 
      no member named 'isunordered' in the global namespace
```

I am not sure if it is an issue with Xcode or Eigen, but I tried specifically pointing to homebrew's eigen installation and no luck.

**Comment by dfm** [comment]
This looks like an xcode/compiler configuration issue from first glance. Can you try install using conda-forge? If not, I'll try to push a Mac binary to PyPI shortly.

**Comment by kennychowdhary** [comment]
Works with conda!
