### ISSUE TITLE
Unable to update values on a custom mean model.

### ISSUE THREAD

**Issue by arkottke** [dfm/george#142]
I implemented `george.modeling.Model` to provide a custom model. During optimization, it tries to call `self.set_vector`. I believe that this should be `self.set_parameter_vector`. The potential bug [here](https://github.com/dfm/george/blob/ebb5d02ef384879265f1fa9add4cee2cbc6bd1d7/src/george/modeling.py#L123):
```python
for i, v in enumerate(vector):
    vector[i] = v + _EPS
    self.set_vector(vector)
    value = self.get_value(*args, **kwargs)
    vector[i] = v
    self.set_vector(vector)
    grad[i] = (value - value0) / _EPS
```

**Comment by dfm** [comment]
Yes - definitely a bug! This was fixed in https://github.com/dfm/george/pull/90 but I never merged that because I got too far behind on PRs :/ I'd be happy to accept an updated one directed at the `main` branch.

**Comment by arkottke** [comment]
Sure, I will send a PR to fix this issue.
