### ISSUE TITLE
How to copy a GP object?

### ISSUE THREAD

**Issue by syrte** [dfm/george#144]
What is the best solution to copy a george.GP object? e.g., I have a trained GP object, then I want to make some changes (e.g., kernel or kernel params) to it but also keep the original one for comparision.

How about the standard library function `copy.deepcopy`? Thanks!

**Comment by dfm** [comment]
Good question! I think that a `deepcopy` should work just fine. Did you find that it didn't work as expected?

**Comment by syrte** [comment]
Thanks for the reply! A minor issue is that it will copy the input arrays as well, which could be unnecessary sometimes. It is usually not a problem as I see.
