### ISSUE TITLE
Circulant embedding for fast sampling?

### ISSUE THREAD

**Issue by shoyer** [dfm/george#15]
One thing we're interested in doing is sampling the conditional distribution of a GP at regular intervals in multiple dimensions, e.g., at every point in a 1000x1000 grid. This is infeasible with the naive methods currently in George, because it would require constructing a covariance matrix with 10^12 elements.

However, it is indeed possible to sample realizations at regularly space intervals in N-dimensions very quickly the using a trick involving the FFT. The technique is known as circulant embedding (see, e.g., https://www.stat.washington.edu/research/reports/2005/tr477.pdf) and is implemented in several R packages, notably `RandomFields`.

Unfortunately, we haven't found any elegant Python implementations. Though I'm guessing that this is something that you don't personally need, it seems like it might be a natural fit for a feature to add to George, to complement its fast training. Thoughts?

**Comment by dfm** [comment]
In the many years since this issue was opened, I've thought about this a lot. I'd love to chat offline but I don't think that this is something that I'll add to george directly.
