### ISSUE TITLE
python setup.py install error -- couldn't find Eigen headers

### ISSUE THREAD

**Issue by allisony** [dfm/george#151]
The vendor/eigen/ directory is empty and this raises the RuntimeError "couldn't find Eigen headers". I see in earlier versions that this directory is not empty, and I was able to install version 0.3.1 successfully.

**Comment by dfm** [comment]
To install from source, follow the instructions from the docs: https://george.readthedocs.io/en/latest/user/quickstart/#from-source

In particular, don't forget the `--recursive` in the clone (that's the issue you're seeing) and don't run `setup.py` directly (use `python -m pip install -e .` instead!).

**Comment by allisony** [comment]
Thank you, Dan!
