### ISSUE TITLE
Adding custom kernel issue

### ISSUE THREAD

**Issue by allisony** [dfm/george#152]
I'm following the instructions here (https://george.readthedocs.io/en/latest/tutorials/new-kernel/#kernel-specification) for adding a new kernel. I've saved a .yml file in /george/kernels/ and recompiled george, but the new kernel isn't showing up under george.kernels. Are there other instructions somewhere? Or any idea what I'm doing wrong?

**Comment by dfm** [comment]
It looks like you'll now need to run `python generate_kernels.py` in the root directory of the repo first. That's not documented, but it should do the trick! You might need to run the following to install dependencies first:

```bash
conda install pyyaml jinja2
```

**Comment by allisony** [comment]
Yes, that worked (I already had pyyaml and jinja2 installed). Thanks so much!
