### ISSUE TITLE
[documentation] meaning of HODLRSolver parameters: min_size and tol

### ISSUE THREAD

**Issue by syrte** [dfm/george#158]
Hi Dan, thanks for the superb algorithm and package!
I am confused about the meaning of the `HODLRSolver` parameters `min_size=100, tol=0.1, seed=42`.
As far as I noticed, tol=0.1 may lead to some difficulties in optimizing the parameters sometimes, and a smaller tol e.g., 1e-3 can help.

I confess that I didn't go through the original algorithm paper (I skimmed quickly, but the answer is not obvious to me). But I did search through the repo, issues, and document.
What do they mean and when should I change the default numbers? Maybe it would be helpful for the users if adding some more explanation in the documentation.
Thanks again!

**Comment by dfm** [comment]
Thanks! Yes - would you be interested in opening a PR with this info added as a docstring to the HODLRSolver:

https://github.com/dfm/george/blob/769a71365d7f89fd9fc7ba9d38e8b5f648350aef/src/george/solvers/hodlr.py#L13

**Comment by syrte** [comment]
sure. will do it later this week.
