### ISSUE TITLE
Uncertainties blow up

### ISSUE THREAD

**Issue by temuller** [dfm/george#166]
Hi, I am trying to fit some supernova light curves in 2D (flux as a function of wavelength and time) and george works nicely, except that the uncertainties blow up wherever there is no data. I have tried different constrains on the hyperparameters, but without good results. I am using a matern 5/2 kernel on the time axis and squared exponential on the wavelength axis.

See below an image with an extract of a single light curve from the 2D fit. Any ideas on how I can improve this? As a reference, my code can be found here: https://github.com/temuller/piscola/blob/master/src/piscola/gaussian_process.py#L92

![Screenshot from 2024-02-05 16-50-44](https://github.com/dfm/george/assets/20286110/be117414-18d0-4c8a-bef9-af193355adbc)

**Comment by dfm** [comment]
@temuller — This actually looks as expected to me! A GP isn't really a good model for non-stationary signals like these, but that's more of a research question than a george issue. Please feel free to email me if you'd like to chat about it!
