### ISSUE TITLE
PyPI tarball missing `kernel_interface.cpp`

### ISSUE THREAD

**Issue by smahler207** [dfm/george#176]
Hey! I tried running `pip install george` on an ARM system and I saw this error: 

```
      -- Configuring done (5.8s)
      CMake Error at /tmp/test/lib/python3.11/site-packages/pybind11/share/cmake/pybind11/pybind11Tools.cmake:181 (add_library):
        Cannot find source file:
          src/george/kernel_interface.cpp
      Call Stack (most recent call first):
        CMakeLists.txt:12 (pybind11_add_module)
```
When I download from the repo and build from source, it worked just fine. When I inspected the tarball from PyPi, I noticed the file is indeed missing. I also confirmed the issue existed on x86; I ran `pip install george --no-binary=george` and saw the same error message.

I don't know why the PyPi tarball is missing this .cpp file, but hopefully adding it will fix the issue.

**Comment by dfm** [comment]
Thanks for reporting! I fixed this with #177 and I'll make a new release shortly.
