### ISSUE TITLE
pip ValueError

### ISSUE THREAD

**Issue by benjaminpope** [dfm/george#23]
Installed via sudo pip install george. No problem when I manually installed from source, but got this for the pip version:
## In [1]: import george

ImportError                               Traceback (most recent call last)
<ipython-input-1-b8f64cf9ebb9> in <module>()
----> 1 import george

/usr/local/lib/python2.7/dist-packages/george/**init**.py in <module>()
     11     **all** = ["kernels", "GP", "BasicSolver", "HODLRSolver"]
     12 
---> 13     from . import kernels
     14     from .gp import GP
     15     from .basic import BasicSolver

/usr/local/lib/python2.7/dist-packages/george/kernels.py in <module>()
     16 from functools import partial
     17 
---> 18 from ._kernels import CythonKernel
     19 from .utils import numerical_gradient
     20 

ImportError: No module named _kernels

**Comment by dr-guangtou** [comment]
Hi! I just tried to install George using the source code, got no error during the installation, but got the same error when I tried to import it; Don't know if I did anything wrong? 

Installed /Users/songhuang/anaconda/lib/python2.7/site-packages/george-0.2.1-py2.7-macosx-10.5-x86_64.egg
Processing dependencies for george==0.2.1
Finished processing dependencies for george==0.2.1
.
.
.
In [5]: import george
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-ad8e8ccfaf59> in <module>()
----> 1 import george

/Users/songhuang/dropbox/work/temp/python/dfm_george/george/__init__.py in <module>()
     11     __all__ = ["kernels", "GP", "BasicSolver", "HODLRSolver"]
     12
---> 13     from . import kernels
     14     from .gp import GP
     15     from .basic import BasicSolver

/Users/songhuang/dropbox/work/temp/python/dfm_george/george/kernels.py in <module>()
     16 from functools import partial
     17
---> 18 from ._kernels import CythonKernel
     19 from .utils import numerical_gradient
     20

ImportError: No module named _kernels

**Comment by dfm** [comment]
Are you still in the source directory when you're trying to import? In that case, the local module will override the installed one.
