### ISSUE TITLE
Covariance bug? (not sure if bug)

### ISSUE THREAD

**Issue by benjaminpope** [dfm/george#28]
Hi Dan,

Perhaps this is a feature not a bug - but I have been playing around with george for K2 and one thing we want to do is to clip outliers by fitting a GP to the raw obs and looking for where points lie > n sigma from the predictive mean.

I notice that george has some funny behaviour when you try and evaluate the posterior covariance at points exactly in the training input array - I have attached a little script where george freaks out and gets zero covariance where GPy doesn't. If you perturb the prediction inputs even slightly from the training inputs it has a nice smooth curve with sensible covariance as expected.

I'm not sure if this is a bug or a feature depending on the tiny default yerr argument?

Cheers,

Ben

```
import numpy as np 
import matplotlib.pyplot as plt 
import george
from george import kernels
import GPy

amp = 0.1
signal = 2.
nsamp = 100

x = np.linspace(0,1,100)

y = signal*x**2.-signal*x**3. + np.random.randn(100)*amp

k1 = kernels.WhiteKernel(0.01)
k2 = 1.0*kernels.ExpSquaredKernel(1.0)
kernel = k1+k2

gp = george.GP(kernel)

gp.compute(x,yerr=0.1)

xpred = x+ 0.00001*np.random.randn(x.shape[0])
x[0], x[-1] = 0.,1.
ypred,ycov = gp.predict(y,xpred)
yerr = np.sqrt(np.diag(ycov))
samples = gp.sample_conditional(y,xpred,size=nsamp)

kernel2 = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)
m = GPy.models.GPRegression(np.array([x]).T,np.array([y]).T,kernel2)

mmean, mvar = m.predict(np.array([xpred]).T)
mmean,mvar  = mmean.flatten(),mvar.flatten()


plt.figure(0)
plt.clf()
plt.plot(x,y,'.k')
plt.plot(xpred,ypred,'-r')
plt.plot(xpred,mmean,'-b')
plt.fill_between(xpred,ypred+yerr,ypred-yerr,color='r',alpha=0.2)
plt.fill_between(xpred,mmean+mvar,mmean-mvar,color='b',alpha=0.2)

for j in range(nsamp):
    plt.plot(xpred,samples[j,:],'-r',alpha=0.01)
plt.xlabel('x')
plt.ylabel('y')
plt.legend(['Data','Model'],loc='best')
plt.draw()
plt.show()
```

**Comment by dfm** [comment]
When I run this example with the current version of george, I'm not seeing any issues, but please feel free to update with the expected behavior if this is still something you care about after all these years ;-)

I'm closing this as "stale". If anyone runs into an issue like this, please feel free to re-open.
