### ISSUE TITLE
Changepoints for george kernels

### ISSUE THREAD

**Issue by StuartLittlefair** [dfm/george#31]
We're using george for an interesting test case. We're modelling eclipsing binaries to measure component masses, but the primary star is accreting, which produces a source of flickering (red noise). 

The accreting nature is key for us, as there is a bright spot where the accretion stream from the secondary star hits the accretion disc. Timing the ingress of the bright spot eclipse allows us to measure the mass ratio.

George provides the GP to model the red noise. Here's the issue - when the primary star is eclipsed, the flickering is also hidden. But because GPs are stationary, the GP 'wants' to have large amplitude variations during eclipse, and thus the GP tends to fit the bright spot ingress, which occurs during primary eclipse.

What we need to do is implement **change points** - discrete times where the hyper parameters of the GP change. There's a nice description of how to define kernel functions with change points in Section 4 of Garnett, Obsorne & Roberts (http://www.robots.ox.ac.uk/~parg/pubs/changepoint.pdf). So far we have implemented this in a PythonKernel, but it is **slow**. We'd like to implement changepoints for all native, stationary, george kernels.

I've opened this issue to discuss ways of going about this. I'd appreciate some tips as to where to start in the george codebase, but also the API needs some thought. The obvious thing to do would be to supply a list of hyper parameters, and an equal length list of change points, but this clashes somewhat with the way the API deals with ndims > 1.

**Comment by dfm** [comment]
I finally got around to this years later. I have a tentative (untested, undocumented) implementation of this in the master branch. It uses the `block` keyword argument for stationary kernels. I'm working on documenting this so I'll update here when I have it written up.

**Comment by StuartLittlefair** [comment]
This is great news! I'm a bit time starved at the moment, so I'll wait until it's documented to implement it and test against our naive python implementation.

**Comment by StuartLittlefair** [comment]
Didn't realise this issue was still open! These work very well and have been used in our production code for >6 months now
