### ISSUE TITLE
Add local Gaussian kernel?

### ISSUE THREAD

**Issue by sharonxuesong** [dfm/george#33]
As described in equation (14) in Czekala et al. 2015:
http://arxiv.org/pdf/1412.5177v1.pdf

This would be of tremendous help for modeling spectrum (and taking care of the spectral line residuals properly)! 

Thanks,
Sharon

**Comment by dfm** [comment]
Sorry I didn't get around to this for so many years! This is implemented on the master branch: http://george.readthedocs.io/en/latest/user/kernels/#george.kernels.LocalGaussianKernel and the new version of george makes it slightly easier to implement your own kernels: http://george.readthedocs.io/en/latest/tutorials/new-kernel/

**Comment by sharonxuesong** [comment]
Hi Dan,

Wow thanks a bunch! I saw the kernel implementation in the new george
package and thought that was your way to answering the ticket.
It's so funny - I just gave a seminar on GP and your packages (emcee,
george, celerite, mostly george) YESTERDAY here at DTM and here you go LOL.

Have a nice day!

Cheers,
Sharon

**Comment by dfm** [comment]
Awesome! And again, I'm sorry that I didn't respond formally until now.
