### ISSUE TITLE
Installation erorr - Not able to import george library

### ISSUE THREAD

**Issue by EskreisWinkler** [dfm/george#38]
I am trying to follow the step by step instructions from http://dan.iel.fm/george/current/user/quickstart/#installation
and am encountering errors when importing the george library. The command line output is:

>>> import george
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "george/__init__.py", line 13, in <module>
    from . import kernels
  File "george/kernels.py", line 18, in <module>
    from ._kernels import CythonKernel
ImportError: No module named _kernels

Any advice would be much appreciated!

**Comment by dfm** [comment]
Did you start Python in the source directory? Try `cd`ing to a different directory first.

**Comment by EskreisWinkler** [comment]
That worked. Thank you!

**Comment by dbrown-astro** [comment]
I'm having a similar issue, but it persists whether I start Python in the source directory or not.

I've installed the 1.0-dev branch. When I then open a new terminal and try to import george in python I get

>>> import george
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//Users/David/Work/Programs/Python/george/george/__init__.py", line 18, in <module>
    from . import kernels
  File "//Users/David/Work/Programs/Python/george/george/kernels.py", line 30, in <module>
    from .cython_kernel import CythonKernel
ImportError: No module named cython_kernel

**Comment by EskreisWinkler** [comment]
In the file kernels.py in the code I pulled the line “from ._kernels import CythonKernel”.


On Feb 24, 2017, at 9:07 AM, dbrown-astro <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm having a similar issue, but it persists whether I start Python in the source directory or not.

I've installed the 1.0-dev branch. When I then open a new terminal and try to import george in python I get

import george
Traceback (most recent call last):
File "", line 1, in
File "//Users/David/Work/Programs/Python/george/george/init.py", line 18, in
from . import kernels
File "//Users/David/Work/Programs/Python/george/george/kernels.py", line 30, in
from .cython_kernel import CythonKernel
ImportError: No module named cython_kernel

**Comment by dbrown-astro** [comment]
Thanks, I'll try that.

**Comment by dbrown-astro** [comment]
That seems to have worked. Thanks again.

**Comment by EskreisWinkler** [comment]
After installation I still get errors related to this issue when i run nosetests - v george, but in python I am able to import george with no problem

On Feb 24, 2017, at 9:26 AM, dbrown-astro <notifications@github.com<mailto:notifications@github.com>> wrote:


That seems to have worked. Thanks again.

**Comment by dfm** [comment]
A few comments. The kernels extension has be renamed to `cython_kernels` in v1.0-dev so it looks like there's probably an issue with multiple versions installed. It helps to run `pip uninstall george` multiple times until you get an error and then reinstall the dev version. This isn't a problem with george - it's just the nightmare that is Python packaging. As for the nosetests issue. There are often problems with _which_ version of the package is being imported and tested. I'm using pytest now for 1.0-dev testing because it seems to be more consistent.
