### ISSUE TITLE
Add a function from outside code

### ISSUE THREAD

**Issue by mlewis1729** [dfm/george#39]
How would I add a function from outside code?
I added
# include "Dawson.h"

to kernels.h in the templates file.
and then added Dawson.h and Dawson.cpp to the george/include/ directory, and reran the setup.py script.
It seems to run to completion, so that's good.
However, when I try to import george in python, I get the following error:

> > > import george
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "build/bdist.linux-x86_64/egg/george/**init**.py", line 18, in <module>
> > >   File "build/bdist.linux-x86_64/egg/george/kernels.py", line 31, in <module>
> > >   File "build/bdist.linux-x86_64/egg/george/cython_kernel.py", line 7, in <module>
> > >   File "build/bdist.linux-x86_64/egg/george/cython_kernel.py", line 6, in **bootstrap**
> > > ImportError: /home/mjlewis/.python-eggs/george-1.0.0.dev0-py2.7-linux-x86_64.egg-tmp/george/cython_kernel.so: undefined symbol: _Z6Dawsond

I assume I need to modify kernels.py or maybe **init**.py.
Any suggestions?

**Comment by dfm** [comment]
This is now a bit easier. Take a look at the example here that includes special functions from boost: https://github.com/dfm/george/blob/master/kernels/MaternGeneral.yml.example
