### ISSUE TITLE
simple model with multiple predictors

### ISSUE THREAD

**Issue by inti** [dfm/george#4]
Hi,
I am interested on trying your package, looks exiting!

let say I want to do y ~ X, with y a univariate output and X a matrix. For example like:

``` python
# dimensions
n1, n2 = 10,50
# predictors
X = np.sort(np.random.rand(n1*n2)).reshape(n1,n2)
# linear coefficients
B = np.random.normal(0,1,size=n2)
# oupout and linear function of coefficients and predictors + some noise
y = np.dot(X,B) + np.random.normal(0,.5,size=n1)

```

how do I go about fitting the GP? in particular
- I do not have error bars for the y's, so I am not sure how to call the gp.compute
- How do I specify the dimension of the kernel?
- Do you have a linear kernel, i.e., XX', I want to try that as well.

This looks a neat addition to the emcee, which is how I want to try it out.

Thanks a lot in advance

**Comment by dfm** [comment]
This is a very old issue but there are docs here if anyone is interested: http://george.readthedocs.io/en/latest/user/kernels/#common-parameters
