### ISSUE TITLE
pip cannot find george

### ISSUE THREAD

**Issue by scopatz** [dfm/george#40]
I on ubuntu, installed libeigen-dev on the system, am using miniconda, Python v3.5.

```console
scopatz@agenor ~ $ pip install george
Collecting george
  Could not find a version that satisfies the requirement george (from versions: )
No matching distribution found for george
```

Also, it would be nice if there was a conda package for this. Conda is much better suited to this use case than pip is. My 2 drachmas, though :)

**Comment by shoyer** [comment]
I wrote a conda recipe for an old version of george and put it in the [conda-recipes repo](https://github.com/conda/conda-recipes/tree/master/george).

**Comment by scopatz** [comment]
Yeah, it seems to be for v0.1.1.  I am not sure what progress has been made since then.

**Comment by scopatz** [comment]
This was an error with my system. Sorry about that. But still a conda package would be really really nice.
