### ISSUE TITLE
Entropy calculation in / from George

### ISSUE THREAD

**Issue by scopatz** [dfm/george#42]
Hello All, Say that I have a GP object, how do I go about computing its H.  Do I have to manually integrate over dy something like `-np.exp(gp.lnlikelihood(y)) * gp.lnlikelihood(y)`? Or am I barking up the wrong tree?

**Comment by davidwhogg** [comment]
If the hypothesis is that y is drawn from the GP, then the empirical estimate of the entropy (under that assumption) is (I think) the mean of the ln likelihood values.  (You get the p in p ln p by the fact that you have a fair sampling.)  But you are better looking in a textbook than here!

**Comment by scopatz** [comment]
Thanks @davidwhogg - I think that I have figured this out.

**Comment by scopatz** [comment]
namely via this gist: https://gist.github.com/GaelVaroquaux/ead9898bd3c973c40429
