### ISSUE TITLE
Interest in Leave One Out Cross Validation score and jackknife matrix?

### ISSUE THREAD

**Issue by mclaughlin6464** [dfm/george#46]
I've been working with Leave One Out Cross Validation's (LOOCV) with George. In Gaussian Processes it is possible to analytically find the leave one out estimator without re-doing the covariance matrix inversion. It's been fairly easy to write up so I was considering adding them to george directly. However, I do not know if they'd be considered redundant with the existing `lnliklihood` functions. Should I implement them?

Additionally, I've also been working on a similar calculation that can produce a jackknife covariance matrix from leave one estimates. This is slightly more complicated, but I'm interested to see if they provide better error estimates than the covariance matrix produces by the gaussian process. Is there interest in this feature, too?

**Comment by dfm** [comment]
Hi Sean, Sorry about the horribly slow response! If I remember correctly, this involves low-rank updates to the Cholesky factorization. I don't know how to do this with the HODLR solver so I'm reluctant to try to add something, but if you had something else in mind, let me know! Also, if you ever wrote this up somewhere, I'd be happy to link to it from the docs.

**Comment by mclaughlin6464** [comment]
Dan,
Thanks for replying! I had forgotten about posting this. When I worked this out and implemented it, I found it didn't work out well in practice, especially the jackknife portion. So, I'd consider this a non-essential add to george. I hadn't considered your HODLR concerns, either!
