### ISSUE TITLE
Calculations of the gradient of the likelihood

### ISSUE THREAD

**Issue by jdavidrcamacho** [dfm/george#47]
Hello!

I've been trying to develop my own version of using gaussian processes in python and for that I've been using george as a guide and comparison for the results I have.

Right now I got into a problem calculating the gradient of the marginal likelihood and I don't really know the source of it or why it happens.

To compare my results with george's results I've created a kernel equal to george's `ExpSine2Kernel` that I've named `ExpSineGeorge` and can be found here:
[https://github.com/jdavidrcamacho/Tests_GP/blob/master/Programs%20being%20tested/Kernel.py#L242](url)

On it I've created the kernel and the derivatives that are going to be used to calculate the gradient.

The tests to compare both versions are here:
https://github.com/jdavidrcamacho/Tests_GP/blob/master/Programs%20being%20tested/tests.py#L17

Using the kernel `ExpSineGeorge(2.0/1.1**2, 7.1)`  and `ExpSine2Kernel(2.0/1.1**2, 7.1)`, when making the calculations in both version I get the same marginal likelihood, in the example in the link it will be `-54.31687`. But in the calculation of the gradient I get `-1.62352 -120.41732` in my version and `-2.68350 -854.96297` in george.

As far as I can see the calculation of the gradient are correct (I based myself on Rasmussen&Williams just like george) and I even used some of george's code to make it that can be found here:
[https://github.com/jdavidrcamacho/Tests_GP/blob/master/Programs%20being%20tested/Likelihood.py#L37](url)
and to be more precise I used the final version of the calculation of the gradient equal to george (as can be seen in line 59 of the previous link). My calculations of the covariance matrix as far as I can see are  correct, if it wasn't I think i shouldn't get the same marginal likelihood of george because  when calculating the marginal likelihood I calculate it.

**The important detail I've discovered and that I don't know why is:**
In the kernels `ExpSine2Kernel` and `ExpSineGeorge`  we are going to have two derivatives, one in order to `gamma` and another in  order to `P` (I don't use amplitude in them to simplify things), since both kernel's expressions are equal so are going to be its derivatives.
I've check it in george's link [https://github.com/dfm/george/blob/master/include/kernels.h#L414](url) and as far as I can see both kernel's derivatives are equal.
There is only one I way I manage to get  the same results as george. If I go to the expressions of my derivatives, and in the equation of the derivative in order of gamma I multiply it by `gamma`, and in the equation of the derivative in order of P I multiply it by `P`, I manage to have exactly the same results of  the gradient of george.

You can go to [https://github.com/jdavidrcamacho/Tests_GP/blob/master/Programs%20being%20tested/Kernel.py#L255](url) and check it for yourself. Runing the tests.py with the code as it is you get different results, if you remove the hastags  in the `return`  you will be multiplying my derivatives by `gamma` and `P` and run the tests.py again you get the same result as george.

Any help to help me understand why this happens or if I'm doing something wrong would help me a lot.
Cheers

**Comment by dfm** [comment]
The derivatives are with respect to `ln(gamma)` and `ln(P)` because `gamma` and `P` should always be greater than 0.

**Comment by jdavidrcamacho** [comment]
Thanks! That solved my problems

Cheers :smile:
