### ISSUE TITLE
Using the dim keyoword with multiple dimensional kernels.

### ISSUE THREAD

**Issue by cjbaxt** [dfm/george#48]
When applying george kernels to multiple dimensional inputs, it is possible to apply kernels only to specified dimensions using the dim keyword. It is not clear from the documentation that dim should start at 0. 

Even if I give it ndim = 3, where dim should be set to 0,1 or 2 - the code does not throw an error if I set dim to 1,2 and 3 (in my respective kernels).

**Comment by dfm** [comment]
This is fixed on the master branch. Thanks!
