### ISSUE TITLE
Metric for radial kernels

### ISSUE THREAD

**Issue by msotov** [dfm/george#51]
When using the radial kernels it is not clear how to input the metric. For example, if the amplitude and time length of my model are (a, t), should I set the exponential squared kernel as 

k = a^2 * kernels.ExpSquaredKernel(t^2),

or

k = a * kernels.ExpSquaredKernel(t) ?

The same happens with the rest of the radial kernels. The documentation doesn't really clarify it. Thank you.

**Comment by dfm** [comment]
It is a bit buried but the docs do say that the parameter for radial kernels is the _variance_. Therefore, if you want:

`k(dt) = a^2 * exp(-dt^2/c^2)`

 then you want to use

```
a = ...
c = ...

kernel = a**2 * kernels.ExpSquaredKernel(c**2)
```
