### ISSUE TITLE
ExpSine2Kernel true implementation

### ISSUE THREAD

**Issue by pilchat** [dfm/george#52]
I'm using George 0.2.1. I need the periodic kernel:

k(dt) = exp{ - Gamma * sin^2( pi*dt / period ) }

In the documentation page I find the ExpSine2Kernel kernel, whose name indicates that it is the kernel for my case. Nonetheless, the formula reported in the documentation page has a "sin" rather than an "exp" as outer function:

k(dt) = sin{ - Gamma * sin^2( pi*dt / period ) }

 Is it exactly how the kernel is implemented, or is it a typo of the doc?

I also checked the doc page of George 1.0, where the bona-fide typo has been corrected from "sin" to "exp". Can you please clarify this?

Thanks a lot

**Comment by dfm** [comment]
The "outer" function is an exp and I've already merged a fix to this but I guess I haven't pushed it to the docs page. I'll get on that. Sorry!

**Comment by pilchat** [comment]
thanks. i'll close the issue
