### ISSUE TITLE
Stable version install

### ISSUE THREAD

**Issue by EskreisWinkler** [dfm/george#53]
I have tried downloading the stable version using "pip install george" and it completes the install and says "Successfully installed george-0.2.1" but I cannot find where the package was downloaded to. I am on a mac and was in my home directory when I ran the install line.

**Comment by dfm** [comment]
pip buries installed packages in your current Python installation. If you want to have the source code, clone from here. Why do you need to find where it was installed?

**Comment by EskreisWinkler** [comment]
You’re right. It wasn’t clear to me that the download had completed but when I tried running the code everything looks like it works great!

Thanks
Jon

On Feb 1, 2017, at 6:45 PM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


pip buries installed packages in your current Python installation. If you want to have the source code, clone from here. Why do you need to find where it was installed?
