### ISSUE TITLE
Would this be the correct way to have multiple independent variables with independent kernels?

### ISSUE THREAD

**Issue by mar-ses** [dfm/george#56]
Say I have timeseries where two variables, `f` and `x` vary with time `t`. I seek to use Gaussian processes to isolate noise varying with time, but also noise correlated with variations in `x`. So essentially I want my GP to have independent variables `x` and `t`, and I want each to have an associated `ExpSquaredKernel`. 

I don't know how to format latex-like maths on github but this is what I want my covariance matrix to look like:

`k(X_i, X_j) = k(x_i, t_i, x_j, t_j) = k_1(x_i, x_j) + k_2(t_i, t_j)
`

Where `k_1(x_i, x_j) = A_x * exp(-(x_j - x_i)**2/(2*var_x))` 
and `k_2(t_i, t_j) = A_t * exp(-(t_j - t_i)**2/(2*var_t))`

So that my hyperparameters are `(A_x, var_x, A_t, var_t)`.

The problem is how to do this in george. Here's what I'm currently trying (since I need `ndim=2`, I'm putting trying to lock-out the "other" variable from each ExpSquaredKernel):

        k_spatial = A_x * kernels.ExpSquaredKernel(metric=[var_x, np.inf], ndim=2)
	    k_temporal = A_t * kernels.ExpSquaredKernel(metric=[np.inf, var_t], ndim=2)
        kernel = k_spatial + k_temporal

Then when I set up my regression, I'll need to make sure that the `np.infs` don't change. Is this the recommended way to do this? Or is there some other functionality to do it in george?

**Comment by dfm** [comment]
I'd recommend taking a look at the `1.0-dev` branch. The API will probably still change a little bit over the next few months but it [supports what you want](http://dan.iel.fm/george/dev/user/kernels/#common-parameters)! Sorry that there isn't a better way with the current version.

**Comment by mar-ses** [comment]
I installed the 1.0 dev branch, but I'm getting a problem.

I have two computers, one running Ubuntu 16.10 and one running Ubuntu 14.04. The one running 16.10 had no trouble, but the one running 14.04 seems to be having problems. Give me a sec and I'll update with the error message.

**Comment by mar-ses** [comment]
Also, when I try to import george on the 14.04 computer, I get this:

```
In [1]: import george
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b8f64cf9ebb9> in <module>()
----> 1 import george

/home/marko/anaconda3/lib/python3.5/site-packages/george-1.0.0.dev0-py3.5-linux-x86_64.egg/george/__init__.py in <module>()
     17 
     18     from . import kernels
---> 19     from .gp import GP
     20     from .metrics import Metric
     21 

/home/marko/anaconda3/lib/python3.5/site-packages/george-1.0.0.dev0-py3.5-linux-x86_64.egg/george/gp.py in <module>()
      9 from scipy.linalg import LinAlgError
     10 
---> 11 from .solvers import TrivialSolver, BasicSolver
     12 from .models import ConstantModel, CallableModel
     13 from .modeling import supports_modeling_protocol

/home/marko/anaconda3/lib/python3.5/site-packages/george-1.0.0.dev0-py3.5-linux-x86_64.egg/george/solvers/__init__.py in <module>()
      5 from .trivial import TrivialSolver
      6 from .basic import BasicSolver
----> 7 from .hodlr import HODLRSolver

ImportError: /home/marko/anaconda3/lib/python3.5/site-packages/scipy/sparse/../../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/marko/anaconda3/lib/python3.5/site-packages/george-1.0.0.dev0-py3.5-linux-x86_64.egg/george/solvers/hodlr.cpython-35m-x86_64-linux-gnu.so)

```

I have ` 0.18.1-np111py35_1`. A quick google suggest this is something to do with the C compiler (the solutions usually relate to gcc). I don't usually use C or gcc so I'm not sure how to fix this. Any ideas?

**Comment by mar-ses** [comment]
Ok it's fixed, I reinstalled everything and now it seems to work. Not sure what happened.

**Comment by dfm** [comment]
Yes - Use GP.white_noise.
