### ISSUE TITLE
Unexpected ln value for the constant in front of an ExpSquaredKernel

### ISSUE THREAD

**Issue by mar-ses** [dfm/george#57]
Hello, I defined an ExpSquaredKernel like so:

```	
	A_xy_i = 10**(-4.5)
	var_x_i = 18**(-1)
	var_y_i = 18**(-1)

	k_spatial = A_xy_i * kernels.ExpSquaredKernel(metric=[var_x_i, var_y_i], ndim=3, axes=[0,1])
```

But when I print the values I get this:

```
In [1]: k_spatial.get_vector()
Out[1]: array([-11.46024521,  -2.89037176,  -2.89037176])
```

Which doesn't agree with the following:

```
In [2]: A_xy_i

Out[2]: 3.1622776601683795e-05

In [4]: np.log(A_xy_i)

Out[4]: -10.361632918473205
```

This happens every time I define a constant in front of the ExpSquaredKernel. I didn't change the vector value either this is immediately after the definition. Is this supposed to happen? What is the actual conversion from the amplitude to the constant vector? 

Using 1.0-dev branch.

**Comment by dfm** [comment]
The parameter for a constant kernel in multiple dimensions is actually `value/ndim`:

```python
In [1]: np.log(10**(-4.5)/3.)
Out[1]: -11.460245207141314
```
