### ISSUE TITLE
How to apply break points to some of the kernels but not others?

### ISSUE THREAD

**Issue by mar-ses** [dfm/george#58]
Hello,

Say I have a `ndim=3` problem, where kernel `k1` is applied on `axis=[0,1]` and `k2` on axis 3. How would you point bounds on the independent parameters in axes `[0,1]` so that the kernel only applies when the value of axis 3 is `bound_1 < x_3 < bound_2`? I thought the `bounds` argument (I'm using the dev version) would be used for it, but maybe I misread the docs, it seems more like the bounds apply bounds to the hyperparameters (at least I keep getting some sort of dimension mismatch errors when I try to use it). Is there anyway to implement this?

**Comment by dfm** [comment]
I just responded to your email too. This is definitely a mistake in the documentation - sorry! It's been a while since I've used this feature and the docs seem to be out of date. You should use the argument `block` instead of `bounds`. Let me know if that works!
