### ISSUE TITLE
Error in tutorial - hyperparameter optimization

### ISSUE THREAD

**Issue by jmccormac01** [dfm/george#59]
Hi,
I was working through the tutorial on hyperparameter optimisation and there was an issue getting the co2 data with statsmodels (v0.8.0). To read the data I had to use the following:

```python
data = sm.datasets.co2.load()
t = np.array(data.data.date).astype(int)
y = np.array(data.data.co2).astype(float)
```

which is slightly different to what is in the tutorial. I assume statsmodels has changed.  Just thought I'd point this out. 

Cheers,
James

**Comment by dfm** [comment]
Hi James,

I've updated this in the development version. Thanks for pointing it out!
