### ISSUE TITLE
unrecognized flag when solving for white noise component of covariance matrix

### ISSUE THREAD

**Issue by mwanakijiji** [dfm/george#61]
When I want to explicitly solve for the white noise component of the covariance matrix, together with an exponent-squared or Matern kernel, in the call to the GP object I set the flag fit_white_noise=True. Here's the relevant code snippet:

```
def lnlike(p, tPass, y, yerr):
    a, tau = np.exp(p[0:2])
    kernelChoice = kernels.ExpSquaredKernel(tau)
    gp = george.GP(a * kernelChoice, fit_white_noise=True, solver=george.HODLRSolver) 
    gp.compute(np.squeeze(tPass), yerr)
    return gp.lnlikelihood(y - model_fit(tPass)) 
```
which returns the error
`TypeError: __cinit__() got an unexpected keyword argument 'fit_white_noise'`

Has this option been deprecated? Do I access the sigma^2*I matrix some other way? (The other kernel parameters converge if I just don't set that flag, but I can't tell how to access the underlying white noise component.)

**Comment by dfm** [comment]
The `fit_white_noise` argument has been added in [the dev version](https://github.com/dfm/george/tree/1.0-dev) for when you want to fit for an extra sigma^2 on the diagonal, but there hasn't been an official release yet. In the currently released version of george, the best thing is to include another parameter that you add in quadrature to `yerr` or you can use the [WhiteKernel](http://dan.iel.fm/george/current/user/kernels/#george.kernels.WhiteKernel).
