### ISSUE TITLE
Using real world datasets

### ISSUE THREAD

**Issue by ktiwari9** [dfm/george#64]
Hi there,
I am currently trying to understand how to do GP inference on a real world dataset. My dataset has 3 columns: [Latitude,Longitude,Measurements] and stores 59 rows for 59 locations labelled via GPS coordinates. In order to perform GP Regression to infer the hyper-parameters, I am not quite sure if I should directly feed in the raw data or should I preprocess somehow ? 

Please advise.

**Comment by dfm** [comment]
This isn't really an issue with the code. Please take a look at [some general information about GPs](http://www.gaussianprocess.org/gpml/chapters/) and then send me an email with a specific question about your problem if you still need help.

**Comment by ktiwari9** [comment]
Hi Dan,Actually, I have read through the link you shared already. I understand that this is not a problem with the code itself, but I asked there to get some help with the generic flow of GP inference. My problem is that if I directly feed the raw data and do GP inference, the hyper-parameters are too big compared to my dataset variance and if I do min-max normalization of inputs and targets my hyper-parameters are really tiny.  Also, if I constrain my hyper-parameters, they get stuck at constraints and no inference seems to happen. So, I am not quite sure what am I doing wrong here. 
I am just a beginner in GPs and its my first time using a real world dataset. I dont want to bother you but if it is okay, it would be nice if you could give me some pointers. If you want I can share my dataset for you.
Please let me know. Thanks and Regards,
Kshitij TIWARI

**Comment by dfm** [comment]
No problem. Please send me an email directly (my address can be found on my
website) with a more specific definition of your problem and what you've
tried so far. Happy to help, but GitHub isn't the right venue for me.
