### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by JohannesBuchner** [dfm/george#68]
Could you please regenerate the readthedocs pages, the ExpSine2Kernel kernel says sin(sin()) even though this was fixed in the code.

Also, I am curious how many threads george uses by default (all?) and how this can be controlled? I guess this depends on the underlying solver? How can I find out the solver currently used?

**Comment by dfm** [comment]
The docs are correct and have been on read the docs for a while. Thanks!

**Comment by JohannesBuchner** [comment]
Sorry, I meant this page: http://dan.iel.fm/george/current/user/kernels/

![screenshot from 2017-08-09 08-27-32](https://user-images.githubusercontent.com/51015/29107925-d199cb22-7cdc-11e7-846d-803720b4830b.png)

Googling for "george kernels" brings this up first.

**Comment by dfm** [comment]
Done.

**Comment by JohannesBuchner** [comment]
Unfortunately the doc and code are still inconsistent: ExpSine2Kernel changed the meaning of the second parameter from period to log_period. I don't know if this was intentional or not, but the API doc should show this (it does on readthedocs), and perhaps also warn that this changed from 0.2.x to 0.3.x?

**Comment by JohannesBuchner** [comment]
To answer my other original question in case someone else searches for it: The multithreading occurs in Eigen, used by HODLR, used by george, and can be controlled by OMP_NUM_THREADS https://eigen.tuxfamily.org/dox/TopicMultiThreading.html.

**Comment by dfm** [comment]
I'm not going to make any more changes to the old docs. Thanks. 

As for your other question: your comment isn't right. The default solver is the basic solver and that just uses numpy + whatever LAPACK you have installed. This tends to use multiple threads and can be controlled using the environment variable you listed on some systems. The HODLR solver shouldn't ever use multiple threads.

**Comment by JohannesBuchner** [comment]
OK, thanks
