### ISSUE TITLE
Same kernel returns different results with same data

### ISSUE THREAD

**Issue by benmontet** [dfm/george#7]
Officially opening an issue, per earlier conversation:

The following code:

```
import numpy as np
import george
from george.kernels import ExpSquaredKernel

a = 0.1
s = 0.5

x = np.linspace(0, 1000, 10000)
y = np.random.random(10000)*0.1 + 0.5

yerr = 0.1*np.ones(10000)
m = 0.5*np.ones(10000)

for i in xrange(10):
    kernel = a * ExpSquaredKernel(s)
    gp = george.GaussianProcess(kernel, tol=1e-12, nleaf=100)
    gp.compute(x, yerr)
    print gp.lnlikelihood(y-m)
```

returns

```
10124.3121797
10125.0028425
10125.1186467
10125.332759
10125.332759
10125.332759
10125.2206463
10124.5410274
10124.5410274
10123.6107036
```

It's interesting that there is the same result returned multiple times, making me think that it's some small random number that's propagating through the matrix operations (although that's just a guess...). Changing tol or nleaf doesn't seem to affect the results.

**Comment by dfm** [comment]
I'm closing this as "stale". If anyone runs into an issue like this, please feel free to re-open.
