### ISSUE TITLE
API doesn't match documentation

### ISSUE THREAD

**Issue by tayebzaidi** [dfm/george#70]
The API doesn't match the documentation at this point, and the first example for optimizing the hyperparameters fails with an AttributeError.  Specifically, the `p0 = gp.kernel.vector` call fails because `vector` isn't a method of `gp.kernel` anymore. 
 I thought I could just replace it with `gp.kernel.parameter_vector`, but then other parts of the example start to fail.  In any case, the documentation should match the API.

**Comment by dfm** [comment]
Thanks for your concern but the current docs are correct and they live at http://george.readthedocs.io/

**Comment by tayebzaidi** [comment]
You are absolutely correct, and now I'm realizing that I've been using the 2.1 docs forever.  This is definitely not an issue on your end, but is there a way to make the current readthedocs the first one that appears on google when you search "george python"?

**Comment by tayebzaidi** [comment]
Or redirect / add a link to the correct readthedocs on the site that google currently directs to (http://dan.iel.fm/george/current/)?

**Comment by dfm** [comment]
I've added a link to the old docs. Thanks!
