### ISSUE TITLE
Separating prediction contributions in combined kernels

### ISSUE THREAD

**Issue by hposborn** [dfm/george#72]
This isn't really an issue with the code, more of a feature request/question.

Ok so, as george does excellently well, it is possible to combine (sum) multiple kernels, compute the gp with this kernel & data, and then uses the gp to predict new data. But is it possible to use the gp to determine where each of the summed kernels is contributing.

For example, with a simple ExpSq + white noise kernel:

```
import numpy as np; import george

whiten=0.001; amp=0.01; lengthscale=33.1
newgp=amp*george.kernels.ExpSquaredKernel(lengthscale)+george.kernels.WhiteKernel(whiten)
gp=george.GP(newgp,mean=1.0)

#Fake 30-minute sampled lightcurve with white noise, a 38 minute sinusoidal component, and a longer-period sinusoid
ts=np.arange(0,40,0.024)
ys=np.random.normal(1.0,whiten*1.3,len(ts))+np.sin(ts*(1440/38.4350897))*whiten*1.9+np.sin(ts/2.6)*whiten*0.8
yerr=np.tile(whiten,len(ts))[:900]

#Computing and predicting
gp.compute(ts[:900],yerr[:900])
ypred=gp.predict(ys[:900],ts,mean_only=True)
```
What steps do I then take to determine the contributions in the prediction from each kernel?
I really want to take the predicted flux trend and subtract the contributions of the ExpSq kernel, leaving only a white noise component. But in this case, (flux) - (gp-predicted-flux) = 0.

**Comment by hposborn** [comment]
I was sure I was using the up-to-date george-0.3 as I pip installed only last month, but apparently I'm in 0.21 still, and the white noise question is a lot easier to solve [ george.GP(a*george.kernel. ExpSquaredKernel(l), white_noise=whiten) ], but the question still stands for other combined kernel combinations!

**Comment by dfm** [comment]
Thanks for this! I decided to actually implement this directly in george because it's so trivial. I added a tutorial that will work with the master branch of this repo: http://george.readthedocs.io/en/latest/tutorials/mixture/
