### ISSUE TITLE
Installing george from source

### ISSUE THREAD

**Issue by Yvonne-Ng** [dfm/george#73]
Hi, I am installing george from source and when I use test.py -v, one of the test failed:
"tests/test_metrics.py::test_custom_cholesky xfail"
I wonder how do I further debug to figure out what is wrong? 
Thanks

**Comment by Yvonne-Ng** [comment]
Python import error:
>>> import george
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yvonne/george/george/__init__.py", line 17, in <module>
    from . import kernels
  File "/Users/yvonne/george/george/kernels.py", line 26, in <module>
    from .kernel_interface import KernelInterface
ImportError: No module named 'george.kernel_interface'



This is the nosetests error: 

-bash: nonsetests: command not found
yvonnengmac:george yvonne$ nosetests -v george.testing
Failure: ImportError (No module named 'george.kernel_interface') ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named 'george.kernel_interface')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "/Users/yvonne/george/george/__init__.py", line 17, in <module>
    from . import kernels
  File "/Users/yvonne/george/george/kernels.py", line 26, in <module>
    from .kernel_interface import KernelInterface
ImportError: No module named 'george.kernel_interface'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by dfm** [comment]
For your first question: "XFAIL" indicates a known failure - this shouldn't be listed as an actual failure of the test.

For the second: if you want to run the tests in the source directory, you need to use: `python setup.py build_ext --inplace` to get the extensions built in place.

**Comment by Yvonne-Ng** [comment]
Hi 
I apprecaite the quick reply! I quickly ran into a different problem 👍 /Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m/pybind11/detail/common.h:139:10: fatal error:
      'forward_list' file not found
#include <forward_list>

Do you know anything about this? is there a recommended clang c++ lib or pybind11 version? thanks

**Comment by dfm** [comment]
To solve this you need to include the "-stdlib=libc++" command line argument, but the build script should have figured that out already. You could try something like: 

`CFLAGS=-stdlib=libc++ python setup.py build_ext --inplace`

If that doesn't work, I recommend doing some googling because that's all I'd be doing too.

**Comment by LumiWang** [comment]
@Yvonne-Ng I wonder if you have solved the forward_list problem? If so, how? If you could still remember =)

I bumped into exactly the same problem, and as I have almost no experience in cpp, I am awed.
