### ISSUE TITLE
how to create a new kernel if I install george from pip?

### ISSUE THREAD

**Issue by Yvonne-Ng** [dfm/george#75]
I was able to install george with pip, but I cannot find the kernel directory to put .yml file in there. is there a standard way of adding kernels? thanks

**Comment by dfm** [comment]
Unfortunately it is not currently possible to add kernels when you install with pip - you'll need to install from source instead.

**Comment by Yvonne-Ng** [comment]
If someone else compiled it in their files, would moving the kernels.py and kernels.h over from their directory mean that I would have access to the kernel?
Thanks

**Comment by dfm** [comment]
Unfortunately, no. You must recompile the library any time you add a
kernel.
