### ISSUE TITLE
AttributeError: 'BaseMatern52Kernel' object has no attribute 'vector'

### ISSUE THREAD

**Issue by numairmansur** [dfm/george#76]
The example given in the [kernels](http://dfm.io/george/current/user/kernels/#combining-kernels) sections does not work anymore:

```
from george import kernels
k = 2.0 * kernels.Matern32Kernel(5.0)
print(k.vector)
```
I get:
`AttributeError: vector`

**Comment by dfm** [comment]
Take a look at http://george.readthedocs.io - that's where the
documentation lives now.

**Comment by numairmansur** [comment]
Alright thanks !
