### ISSUE TITLE
Missing minus sign in the docs

### ISSUE THREAD

**Issue by tmcclintock** [dfm/george#78]
The [new docs](http://dfm.io/george/current/user/hyper/#optimization) demonstrating how to optimize is missing a minus sign.

This line: ```return -ll if np.isfinite(ll) else 1e25``` should be ```return -ll if np.isfinite(ll) else -1e25```.

**Comment by dfm** [comment]
Not quite! The whole point is that the *negative* log likelihood should be a large *positive* number when the fit is bad. I believe that the docs are correct.

**Comment by tmcclintock** [comment]
Correct I am an idiot.

**Comment by dfm** [comment]
Haha. Not at all! The number of times we've all made that same mistake...
