### ISSUE TITLE
HODLRSolver seems to be unstable

### ISSUE THREAD

**Issue by alexisrosuel** [dfm/george#79]
Hi all ! 

I discovered george recently, thanks for this awesome package !

I am comparing a gaussian process predictions using the standard solver and the optimized HODLRSolver. I saw that that for the exact same problem, the scipy solver gives a "correct" solution, but the HODLRSolver diverges completely. Is it normal ?

Here are more details about the problem I am working on : 

```
import george

cst = george.kernels.ConstantKernel(log_constant=np.log(0.1), ndim=2)
k = george.kernels.Matern52Kernel(metric=2000**2, ndim=2)

kernel = cst_long * k

gp = george.GP(kernel=kernel, fit_mean=True, mean=1, 
               fit_white_noise=True, white_noise=1)

# or 
gp = george.GP(kernel=kernel, fit_mean=True, mean=1, 
               fit_white_noise=True, white_noise=1,
               solver=george.HODLRSolver)

#### Routine to find the optimal hyperparameters
gp.compute(listings_sampled[['x','y']])
# Run the optimization routine.
p0 = gp.get_parameter_vector()
results = op.minimize(likelihood_function, p0, jac=grad_nll, method="L-BFGS-B")
gp.set_parameter_vector(results.x)
##### 

# Finally compute some predictions
gp.predict(...

```

Thanks for your help !

**Comment by dfm** [comment]
This will depend on the specifics of your model, but you could try reducing the `tol` parameter when you use the HODLRSolver (http://george.readthedocs.io/en/latest/user/solvers/#george.HODLRSolver) to see if that makes any difference. The HODLR solver is approximate so it can be unstable for poorly conditioned problems and the gradients can sometimes be noisy!

**Comment by alexisrosuel** [comment]
Hi !

Thanks for your answer, I tried to reduce the tol parameter, and indeed it is converging towards a better solution. But I saw another issue (if needed I will open another issue :) )

1. What is "min size" ? I didn't found any reference in the online doc... I wonder it is linked to the optimization on the matrix (with the explanations of the white paper), but it would be useful to have a short description of what it represents

2. Much more important, the metrics bound are not respected in my case : 
I define my gaussian process like this : 

```
import george
trend = george.kernels.ExpSquaredKernel(metric=[[1000,0],[0,1000]], 
                                        metric_bounds=[(3.45,5),(0,0),(3.45,5)],
                                        ndim=2)
cst_trend = george.kernels.ConstantKernel(log_constant=np.log(10), bounds=[(1, None)], ndim=2)
kernel = trend * cst_trend

gp = george.GP(kernel=kernel, fit_kernel=True, mean=1.09, fit_mean=False, white_noise=np.log(0.128), 
               fit_white_noise=True, solver=george.BasicSolver)
```

then I run the optimisation routine provided here : http://george.readthedocs.io/en/latest/tutorials/hyper/ 

and when finally printing the optimized hyper parameters, I have this : 
`gp.get_parameter_dict()`

```
OrderedDict([('white_noise:value', -1.9894689413922899),
             ('kernel:k1:metric:log_L_0_0', 8.3451651742899315),
             ('kernel:k1:metric:L_0_1', 1.2871675691999613),
             ('kernel:k1:metric:log_L_1_1', 7.6349488377814048),
             ('kernel:k2:log_constant', -3.7643743216323768)])
```

where you can see that `k2:log_constant` is equal to `-3.76`, whereas the bounds where `(1,None)` ...

What do you think ?

**Comment by dfm** [comment]
You need to tell the optimizer about the bounds! Check out the scipy docs.
You can access the list of bounds using gp.get_parameter_bounds().

**Comment by alexisrosuel** [comment]
Ok, I thought the bounds where taken into acount within the gp object, my bad...

Thanks ! We can close the issue then I think :)

**Comment by dfm** [comment]
Great. Thanks!
