### ISSUE TITLE
Import Error ('No module named kernel_interface')

### ISSUE THREAD

**Issue by Enki96** [dfm/george#80]
Hello, 
I installed from source code. When I try to import george in Python I am getting this error: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "george/__init__.py", line 17, in <module>
    from . import kernels
  File "george/kernels.py", line 26, in <module>
    from .kernel_interface import KernelInterface
ImportError: No module named kernel_interface

**Comment by dfm** [comment]
This happens sometimes when you try to import it from the source directory - this isn't specific to george, but true for all packages with compiled extensions.

How did you install george? What have you tried so far?
