### ISSUE TITLE
Where is "Task Kernel" in this repository?

### ISSUE THREAD

**Issue by snpc94** [dfm/george#82]
Hello,
I use this repository, george via RoBO(https://github.com/automl/RoBO), one of the repository to implement bayesian optimization for my research.

In the RoBO, there is a implementation like under this link (see line:100).
https://github.com/automl/RoBO/blob/master/robo/fmin/mtbo.py
This code is used "Task Kernel" imported by george.
I want to know the implementation about this kernel, but I can't find it.
Could you teach me where is the implementation of "Task Kernel" in this repository?

**Comment by dfm** [comment]
There is no "TaskKernel" in george so it must be a custom kernel that they added. If it's not clear from their docs, open an issue on that repository.
