### ISSUE TITLE
PyBind11 API changed and headers not found

### ISSUE THREAD

**Issue by saturnaxis** [dfm/george#84]
I installed the pybind11 dependency, but george would not install (via pip).  PyBind11 has updated the API to change PYBIND11_PLUGIN to PYBIND11_MODULE and moved the location of the generated header files (pybind11.h and numpy.h) into $VIRTUAL_ENV/include/site/python2.7/.

https://pybind11.readthedocs.io/en/stable/upgrade.html

**Comment by dfm** [comment]
This shouldn't cause the code to not install - it's just a deprecation warning! Also: the headers are found using pybind11's methods so that should still be consistent too.

**Comment by saturnaxis** [comment]
I tried installing 3 different ways, via pip, source, and source with include point to the directory with the headers.  All fail.  What should I be doing differently?

[source_build.txt](https://github.com/dfm/george/files/1475450/source_build.txt)
[source_build_Include.txt](https://github.com/dfm/george/files/1475451/source_build_Include.txt)
[pip_build.txt](https://github.com/dfm/george/files/1475452/pip_build.txt)

**Comment by dfm** [comment]
How did you install pybind11? It looks like the directory that you suggest (`$VIRTUAL_ENV/include/site/python2.7/`) is being searched.

**Comment by saturnaxis** [comment]
I tried both via pip and from git.  I get the same error messages.  So I went through kernel_interface.cpp, parser.h, and _hodlr.cpp where the include <pybind11/pybind11.h> statements are located.  I removed the "pybind/" and it seemed to work (building from source without the include).  I've attached the screen output.

[source_build.txt](https://github.com/dfm/george/files/1476194/source_build.txt)

**Comment by dfm** [comment]
That sounds like a bug with your Python environment, because that's not where the headers should be installed! This has been tested on Linux, Mac, and Windows extensively. I'm not sure what to recommend, but I'm glad that you found something that worked for your case.

**Comment by saturnaxis** [comment]
The problem was with pip in my virtualenv.  I upgraded pip to the latest version and it put the headers where they are expected to be (i.e., pybind11/pybin11.h)

**Comment by dfm** [comment]
Great. Thanks for the update!
